Disable Windows ARM64 for now.
Either we need some other way to not depend on WavPack or we need
to figure out why an overlay port fails to apply the very same patch
the in-tree port applies.

The overlay sdl2-mixer fails with the following:

Building sdl2-mixer:x64-windows-ltcg-static@2.8.0#1...
-- [OVERLAY] Loading triplet configuration from: D:\a\dunelegacy\dunelegacy\external\vcpkg\config\triplets\x64-windows-ltcg-static.cmake
-- Installing port from location: D:\a\dunelegacy\dunelegacy\external\vcpkg\config\ports\sdl2-mixer
-- Downloading https://github.com/libsdl-org/SDL_mixer/archive/release-2.8.0.tar.gz -> libsdl-org-SDL_mixer-release-2.8.0.tar.gz...
-- Extracting source D:/a/dunelegacy/dunelegacy/external/vcpkg/vcpkg/downloads/libsdl-org-SDL_mixer-release-2.8.0.tar.gz
-- Applying patch fix-pkg-prefix.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:34 (message):
Error:   Applying patch failed: error: corrupt patch at line 7
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:147 (z_vcpkg_apply_patches)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:8 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:113 (vcpkg_extract_source_archive_ex)
  D:/a/dunelegacy/dunelegacy/external/vcpkg/config/ports/sdl2-mixer/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:170 (include)
error: building sdl2-mixer:x64-windows-ltcg-static failed with: BUILD_FAILED
Elapsed time to handle sdl2-mixer:x64-windows-ltcg-static: 917 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+sdl2-mixer
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[sdl2-mixer]+Build+error+on+x64-windows-ltcg-static&body=Copy+issue+body+from+D%3A%2Fa%2Fdunelegacy%2Fdunelegacy%2Fbuild%2FRelease-x64%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md
You can also submit an issue by running (GitHub CLI must be installed):
  gh issue create -R microsoft/vcpkg --title "[sdl2-mixer] Build failure on x64-windows-ltcg-static" --body-file D:/a/dunelegacy/dunelegacy/build/Release-x64/vcpkg_installed/vcpkg/issue_body.md
-- Running vcpkg install - failed
CMake Error at external/vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
Error:   vcpkg install failed.  See logs for more information:
  D:\a\dunelegacy\dunelegacy\build\Release-x64\vcpkg-manifest-install.log